{
 "title": "Harness FF Proxy",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by Status Code",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by(code) (rate(ff_proxy_http_requests_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests by Endpoint",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by(url) (rate(ff_proxy_http_requests_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum by(le) (rate(ff_proxy_http_requests_duration_bucket[5m]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Payload Size",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum by(le) (rate(ff_http_requests_content_length_histogram_bucket[5m]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SDK Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "SDK Usage",
     "type": "timeseries",
     "description": "Shows which SDKs are using the ff-proxy",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by(sdk_type, sdk_language, sdk_version) (rate(ff_proxy_sdk_usage[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Proxy -> Harness Saas Communication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Forwarded",
     "type": "timeseries",
     "description": "Shows the rate of metrics being forwarded from the Primary Proxy to Harness Saas and if errors are occuring",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum by(error) (rate(ff_proxy_metrics_forwarded{error=\"false\"}[5m]))",
       "legendFormat": "Successfully Forwarded Metrics"
      },
      {
       "expr": "sum by(error) (rate(ff_proxy_metrics_forwarded{error=\"true\"}[5m]))",
       "legendFormat": "Unsuccessfully Forwarded Metrics"
      }
     ]
    }
   ]
  },
  {
   "title": "Primary Proxy Stream Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Harness Saas -> Primary SSE Events",
     "type": "timeseries",
     "description": "Shows SSE Events being received by the Primary Proxy",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(rate(ff_proxy_saas_to_primary_sse_consumer_messages_received{error=\"false\"}[5m]))",
       "legendFormat": "SSE Events Received from Saas"
      },
      {
       "expr": "sum(rate(ff_proxy_saas_to_primary_sse_consumer_messages_received{error=\"true\"}[5m]))",
       "legendFormat": "Failed to Recevie SSE Events"
      }
     ]
    },
    {
     "title": "Primary Proxy-> SDKs",
     "type": "timeseries",
     "description": "Shows SSE Events being forwarded from the Primary Proxy to SDKs. Note this will show data even if you have no SDKs connected to the Primary Proxy",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum(rate(ff_proxy_primary_to_sdk_sse_producer_messages_published{error=\"false\"}[5m]))",
       "legendFormat": "Successfully Forwarded Events"
      },
      {
       "expr": "sum(rate(ff_proxy_primary_to_sdk_sse_producer_messages_published{error=\"true\"}[5m]))",
       "legendFormat": "Unsuccessfully Forwarded Events"
      }
     ]
    },
    {
     "title": "Primary Proxy -> Read Replica Proxy",
     "type": "timeseries",
     "description": "Shows SSE events being forwarded from the Primary Proxy to Read Replica Proxy's",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(rate(ff_proxy_primary_to_replica_sse_producer_messages_published{error=\"false\", topic=\"proxy:sse_events\"}[5m]))",
       "legendFormat": "Successfully Forwarded Events"
      },
      {
       "expr": "sum(rate(ff_proxy_primary_to_sdk_sse_producer_messages_published{error=\"true\", topic=\"proxy:sse_events\"}[5m]))",
       "legendFormat": "Unsuccessfully Forwarded Events"
      }
     ]
    }
   ]
  },
  {
   "title": "Read Replica Stream Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Replica Proxy Events Received",
     "type": "timeseries",
     "description": "Shows SSE events being received by Read Replica Proxy's",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(rate(ff_proxy_replica_sse_consumer_messages_received{error=\"false\", topic=\"proxy:sse_events\"}[5m]))",
       "legendFormat": "Successfully Received SSE Events"
      },
      {
       "expr": "sum(rate(ff_proxy_primary_to_sdk_sse_producer_messages_published{error=\"true\", topic=\"proxy:sse_events\"}[5m]))",
       "legendFormat": "Successfully Received SSE Events"
      },
      {
       "expr": "sum(rate(ff_proxy_primary_to_sdk_sse_producer_messages_published{error=\"false\", topic=\"proxy:primary_to_replica_control_events\"}[5m]))",
       "legendFormat": "Successfully Received Control Events"
      },
      {
       "expr": "sum(rate(ff_proxy_primary_to_sdk_sse_producer_messages_published{error=\"true\", topic=\"proxy:primary_to_replica_control_events\"}[5m]))",
       "legendFormat": "Unsuccessfully Received Control Events"
      }
     ]
    },
    {
     "title": "Read Replica -> SDK",
     "type": "timeseries",
     "description": "Shows SSE events being forwarded by Read Replica Proxy's to SDKs",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum(rate(ff_proxy_replica_to_sdk_sse_producer_messages_published{error=\"false\"}[5m]))",
       "legendFormat": "Successfully Forwarded SSE Events"
      },
      {
       "expr": "sum(rate(ff_proxy_replica_to_sdk_sse_producer_messages_published{error=\"true\"}[5m]))",
       "legendFormat": "Unsuccessfully Forwarded SSE Events"
      },
      {
       "expr": "sum(rate(ff_proxy_primary_to_sdk_sse_producer_messages_published{error=\"false\", topic=\"proxy:primary_to_replica_control_events\"}[5m]))",
       "legendFormat": "Successfully Received Control Events"
      },
      {
       "expr": "sum(rate(ff_proxy_primary_to_sdk_sse_producer_messages_published{error=\"true\", topic=\"proxy:primary_to_replica_control_events\"}[5m]))",
       "legendFormat": "Unsuccessfully Received Control Events"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Writes",
     "type": "timeseries",
     "description": "Show the number of successful and unsuccessful writes to the cache",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum by() (rate(ff_proxy_redis_cache_write_count{error=\"false\"}[5m]))",
       "legendFormat": "Successful Writes"
      },
      {
       "expr": "rate(ff_proxy_redis_cache_write_count{error=\"true\"}[5m])",
       "legendFormat": "Failed Writes"
      },
      {
       "expr": "sum by(cluster) (rate(ff_proxy_redis_cache_remove_count[5m]))",
       "legendFormat": "Deletes"
      }
     ]
    },
    {
     "title": "Cache Reads",
     "type": "timeseries",
     "description": "Shows the number of successful and failed reads made to the cache",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(ff_proxy_redis_cache_read_count{error=\"false\"}[5m]))",
       "legendFormat": "Successful reads"
      },
      {
       "expr": "sum(rate(ff_proxy_redis_cache_read_count{error=\"true\"}[5m]))",
       "legendFormat": "Failed reads"
      }
     ]
    },
    {
     "title": "Memoize Cache Hits",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(job) (rate(ff_proxy_memoize_cache_hit[5m]))",
       "legendFormat": "Cache Hit"
      },
      {
       "expr": "sum by(job) (rate(ff_proxy_memoize_cache_miss[5m]))",
       "legendFormat": "Cache Miss"
      },
      {
       "expr": "sum by(job) (rate(ff_proxy_memoize_cache_hit_with_unmarshal[5m]))",
       "legendFormat": "Cache Hit (But had to unmarshall)"
      },
      {
       "expr": "sum by(job) (rate(ff_proxy_memoize_cache_write_marshal[5m]))",
       "legendFormat": "Remote Cache Hit (wrote to local)"
      }
     ]
    }
   ]
  }
 ]
}